### ISSUE TITLE
Update gold:Gs0114675 / nmdc:sty-11-8fb6t785 Deep subsurface shale (metagenomes)

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#166]
Omics Type(s): metagenomes
Note: Study only goes to OmicsProcessing level.  

Steps:
- [x] Unset `has_output` for omics_processing records
- [x] `update-study`

**Comment by aclum** [comment]
I've used queries:run to update has_output to an empty list on napa, dev, and prod. Unsetting did not work with the endpoint so @eecavanna  and I opted to use $set with an empty list as an alternative.

**Comment by eecavanna** [comment]
Yes, that's my stance. I propose that we `$set` to `[]` for now (because the Runtime allows it) and then — after re-ID-ing takes place — as a separate endeavor, "[clean up](https://github.com/microbiomedata/infra-admin/issues/58)" those empty lists. To identify those empty lists later, someone can either (a) use any logs/records that the re-ID-ing tool generates or (b) use a Python notebook I wrote a few months ago to search the entire database for them (just took a few minutes when run on a NERSC machine).

**Comment by ssarrafan** [comment]
Appears active. Moving to new sprint for review. Please remove from sprint if not active.
