### ISSUE TITLE
Test out jaws-client python module with NMDC workflows

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/nmdc_automation#48]
Test out NMDC Workflows using jaws python module and ensure python module is functioning with our expectations. 

jaws-client python library 
pip install jaws-client --index-url https://code.jgi.doe.gov/api/v4/projects/312/packages/pypi/simple

**Comment by ssarrafan** [comment]
@mflynn-lanl @Michal-Babins what's the status of this issue?  Any updates?

**Comment by mflynn-lanl** [comment]
We're putting this off because of other priorities
________________________________
From: ssarrafan ***@***.***>
Sent: Friday, February 23, 2024 1:40 PM
To: microbiomedata/nmdc_automation ***@***.***>
Cc: Flynn, Mark C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/nmdc_automation] Test out JAWs python module with NMDC workflows (Issue #48)


@mflynn-lanl<https://urldefense.com/v3/__https://github.com/mflynn-lanl__;!!Bt8fGhp8LhKGRg!HnoI17J1Xp1tETpiVdsWd03rdbPLNc9A7sJ18t6Y7Fu5rjfsZq6RDgCMknQ63gPvrNnJp6Lfug9te8OnwhbiG3Vt$> @Michal-Babins<https://urldefense.com/v3/__https://github.com/Michal-Babins__;!!Bt8fGhp8LhKGRg!HnoI17J1Xp1tETpiVdsWd03rdbPLNc9A7sJ18t6Y7Fu5rjfsZq6RDgCMknQ63gPvrNnJp6Lfug9te8OnwkmrosI0$> what's the status of this issue? Any updates?

**Comment by ssarrafan** [comment]
Ok I'll remove from the sprint and add to the backlog. 
@mflynn-lanl @aclum @shreddd

**Comment by aclum** [comment]
was able to confirm that as myself the submit and status commands work as expected.

**Comment by aclum** [comment]
I can also submit jobs as nmdcda and set added the needed library to nmdcda's python environment. Example code is in linked PR.
